openapi: 3.0.3

info:
  title: Digital Detox API
  description: |-
    Digital Detox API allows clients to save, compare and analyse their progress on detox sessions.
  version: 1.0.0

tags:
  - name: Sessions
    description: Save your detox sessions.
  - name: Leaderboard
    description: Compare your detox sessions with other users.
  - name: Statistics
    description: Analyse your detox sessions over time.

paths:
  /sessions:
    post:
      tags:
        - Sessions
      summary: Save detox session
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: username of the user who has completed a detox session
                date:
                  type: string
                  description: date of the detox session
                duration:
                  type: number
                  description: duration in minutes of the detox session
              required:
                - username
                - date
                - duration
      responses:
        "201":
          description: Created

  /leaderboard:
    get:
      tags:
        - Leaderboard
      summary: Retrieve the leaderboard
      parameters:
        - in: query
          name: date
          required: true
          schema:
            type: string
            description: date of the leaderboard
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  date:
                    type: string
                    description: date of this leaderboard
                  leaderboard:
                    type: array
                    items:
                      type: object
                      properties:
                        position:
                          type: number
                          description: leaderboard position
                        username:
                          type: string
                          description: username of the user
                        numberOfSessions:
                          type: number
                          description: number of detox sessions
                        totalDurationOfSessions:
                          type: number
                          description: total duration of detox sessions

  /statistics:
    get:
      tags:
        - Statistics
      summary: Retrieve detox sessions over a time period
      parameters:
        - in: query
          name: username
          required: true
          schema:
            type: string
            description: username of the user whose detox session will be analysed
        - in: query
          name: startDate
          required: true
          schema:
            type: string
            description: start of the date range of detox sessions to be analysed, including the date specified by this value
        - in: query
          name: endDate
          required: true
          schema:
            type: string
            description: end of the date range of detox sessions to be analysed, including the date specified by this value
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                      description: date
                    numberOfSessions:
                      type: number
                      description: number of detox sessions
                    totalDurationOfSessions:
                      type: number
                      description: total duration of detox sessions
